version: 2.1

orbs:
  heroku: circleci/heroku@1.2.3
  aws-ecr: circleci/aws-ecr@6.14.0
  aws-ecs: circleci/aws-ecs@1.4.0

defaults: &defaults
  docker:
    - image: circleci/python:3.8-buster
      environment:
        - DATABASE_URL=sqlite:////tmp/prj.sqlite
        - REDIS_URL=redis://redis:6379

    - image: circleci/redis:4.0.14-alpine3.10
      name: redis

jobs:
  build:
    <<: *defaults

    steps:
      - checkout

      - restore_cache:
          key: deps-{{ checksum "src/requirements.txt" }}

      - run:
          command: sudo apt-get --no-install-recommends install -y locales-all gettext

      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r src/requirements.txt

      - save_cache:
          key: deps-{{ checksum "src/requirements.txt" }}
          paths:
            - "venv"

      - run:
          command: mv src/app/.env.ci src/app/.env

      - run:
          name: Run linters
          command: |
            . venv/bin/activate
            cd src && flake8

      - persist_to_workspace:
          root: .
          paths:
            - "venv"
            - "src"
            - ".circleci"

  unittest:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .

      - run:
          name: Install locale stuff
          command: sudo apt-get update && sudo apt-get --no-install-recommends install -y locales-all gettext

      - run:
          command: |
            . venv/bin/activate
            cd src && py.test -x

  deploy-to-heroku:
    executor: heroku/default # Uses the basic buildpack-deps image, which has the prerequisites for installing heroku's CLI.
    steps:
      - checkout
      - heroku/install # Runs the heroku install command, if necessary.
      - heroku/deploy-via-git # Deploys branch to Heroku via git push.

workflows:
  version: 2
  continuous-delivery:
    jobs:
      - build
      - unittest:
          requires:
            - build
      - deploy-to-heroku:
          requires:
            - unittest
          filters:
            branches:
              only: master
