# Generated by Django 3.0.7 on 2020-08-06 05:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DictBrand',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'wdf_dict_brand',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='DictCatalog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('level', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'wdf_dict_catalog',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='DictMarketplace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
                ('url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'wdf_dict_marketplace',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='DictParameter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('marketplace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wdf.DictMarketplace')),
            ],
            options={
                'db_table': 'wdf_dict_parameter',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='DictSeller',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('marketplace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wdf.DictMarketplace')),
            ],
            options={
                'db_table': 'wdf_dict_seller',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Dump',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('crawler', models.CharField(max_length=20)),
                ('job', models.CharField(max_length=20)),
                ('crawl_started_at', models.DateTimeField()),
                ('crawl_ended_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'wdf_dump',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Sku',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=512)),
                ('article', models.CharField(max_length=20)),
                ('url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wdf.DictBrand')),
                ('marketplace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wdf.DictMarketplace')),
            ],
            options={
                'db_table': 'wdf_sku',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('catalog_level', models.IntegerField(null=True)),
                ('crawled_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dump', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wdf.Dump')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wdf.Sku')),
            ],
            options={
                'db_table': 'wdf_version',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wdf.DictSeller')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wdf.Sku')),
            ],
            options={
                'db_table': 'wdf_seller',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sales', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wdf.Sku')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wdf.Version')),
            ],
            options={
                'db_table': 'wdf_sales',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reviews', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wdf.Sku')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wdf.Version')),
            ],
            options={
                'db_table': 'wdf_reviews',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.FloatField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wdf.Sku')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wdf.Version')),
            ],
            options={
                'db_table': 'wdf_rating',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('price', models.FloatField()),
                ('price_dirty', models.FloatField(null=True)),
                ('discount', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wdf.Sku')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wdf.Version')),
            ],
            options={
                'db_table': 'wdf_price',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('absolute', models.PositiveIntegerField()),
                ('percintile', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('catalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wdf.DictCatalog')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wdf.Sku')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wdf.Version')),
            ],
            options={
                'db_table': 'wdf_position',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wdf.DictParameter')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wdf.Sku')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wdf.Version')),
            ],
            options={
                'db_table': 'wdf_parameter',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='dictcatalog',
            name='marketplace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wdf.DictMarketplace'),
        ),
        migrations.AddField(
            model_name='dictcatalog',
            name='parent',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='wdf.DictCatalog'),
        ),
        migrations.AddField(
            model_name='dictbrand',
            name='marketplace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wdf.DictMarketplace'),
        ),
    ]
