# Generated by Django 3.0.7 on 2020-08-10 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wdf', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='percintile',
            field=models.FloatField(default=None, null=True),
        ),
    ]
