# Generated by Django 3.0.7 on 2020-08-11 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wdf', '0003_catalog_name_can_be_empty'),
    ]

    operations = [
        migrations.AddField(
            model_name='dump',
            name='items_crawled',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='dump',
            name='job_type',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='dump',
            name='state',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='dictcatalog',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
