# Generated by Django 3.0.7 on 2020-08-12 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wdf', '0004_new_fields_in_dump'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sku',
            name='brand',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='wdf.DictBrand'),
        ),
    ]
