# Generated by Django 3.0.7 on 2020-08-20 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wdf', '0005_brand_on_sku_optional'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='parameter',
            constraint=models.UniqueConstraint(fields=('sku', 'version', 'parameter'), name='unique_parameter_version'),
        ),
        migrations.AddConstraint(
            model_name='position',
            constraint=models.UniqueConstraint(fields=('sku', 'version', 'catalog'), name='unique_position_catalog_version'),
        ),
        migrations.AddConstraint(
            model_name='price',
            constraint=models.UniqueConstraint(fields=('sku', 'version'), name='unique_price_version'),
        ),
        migrations.AddConstraint(
            model_name='rating',
            constraint=models.UniqueConstraint(fields=('sku', 'version'), name='unique_rating_version'),
        ),
        migrations.AddConstraint(
            model_name='reviews',
            constraint=models.UniqueConstraint(fields=('sku', 'version'), name='unique_reviews_version'),
        ),
        migrations.AddConstraint(
            model_name='sales',
            constraint=models.UniqueConstraint(fields=('sku', 'version'), name='unique_sales_version'),
        ),
    ]
