# Generated by Django 3.0.7 on 2020-08-20 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wdf', '0006_added_version_constraints'),
    ]

    operations = [
        migrations.AddField(
            model_name='dump',
            name='state_code',
            field=models.IntegerField(choices=[(5, 'Preparing'), (10, 'Prepared'), (15, 'Scheduling'), (20, 'Scheduled'), (25, 'Processing'), (30, 'Processed')], default=0),
        ),
    ]
