# Generated by Django 3.0.7 on 2020-09-20 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wdf', '0007_added_state_codes_for_dump'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dump',
            name='state_code',
            field=models.IntegerField(choices=[(0, 'Created'), (5, 'Preparing'), (10, 'Prepared'), (15, 'Scheduling'), (20, 'Scheduled'), (25, 'Processing'), (30, 'Processed')], default=0),
        ),
        migrations.AddIndex(
            model_name='dictbrand',
            index=models.Index(fields=['url'], name='wdf_dict_br_url_900fe2_idx'),
        ),
        migrations.AddIndex(
            model_name='dictcatalog',
            index=models.Index(fields=['url'], name='wdf_dict_ca_url_459d96_idx'),
        ),
        migrations.AddIndex(
            model_name='dictparameter',
            index=models.Index(fields=['name'], name='wdf_dict_pa_name_ce6341_idx'),
        ),
        migrations.AddIndex(
            model_name='sku',
            index=models.Index(fields=['article'], name='wdf_sku_article_a1e018_idx'),
        ),
    ]
