# Generated by Django 3.0.7 on 2020-09-20 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wdf', '0008_added_dictionary_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictmarketplace',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AddConstraint(
            model_name='dictmarketplace',
            constraint=models.UniqueConstraint(fields=('name', 'slug'), name='unique_marketplace_name_slug'),
        ),
    ]
