# Generated by Django 3.0.7 on 2020-09-24 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wdf', '0009_added_marketplace_constraints'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameter',
            name='parameter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wdf.DictParameter'),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='sku',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wdf.Sku'),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wdf.Version'),
        ),
        migrations.AlterField(
            model_name='position',
            name='catalog',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wdf.DictCatalog'),
        ),
        migrations.AlterField(
            model_name='position',
            name='version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wdf.Version'),
        ),
        migrations.AlterField(
            model_name='price',
            name='sku',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wdf.Sku'),
        ),
        migrations.AlterField(
            model_name='price',
            name='version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wdf.Version'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='sku',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wdf.Sku'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wdf.Version'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='sku',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wdf.Sku'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wdf.Version'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='sku',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wdf.Sku'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wdf.Version'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wdf.DictSeller'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='sku',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wdf.Sku'),
        ),
        migrations.AlterField(
            model_name='sku',
            name='marketplace',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wdf.DictMarketplace'),
        ),
        migrations.AlterField(
            model_name='version',
            name='sku',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wdf.Sku'),
        ),
    ]
