# Generated by Django 3.0.7 on 2020-10-02 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wdf', '0010_foreign_key_now_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictcatalog',
            name='name',
            field=models.TextField(null=True),
        ),
    ]
