# Generated by Django 3.0.7 on 2020-10-02 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wdf', '0011_convert_catalog_name_to_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='absolute',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='reviews',
            field=models.IntegerField(null=True),
        ),
    ]
