# Generated by Django 3.1.2 on 2020-10-12 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wdf', '0012_nullable_reviews_and_catalog_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dump',
            name='crawl_ended_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='dump',
            name='crawl_started_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='dump',
            name='state_code',
            field=models.IntegerField(choices=[(-1, 'Error'), (0, 'Created'), (5, 'Preparing'), (10, 'Prepared'), (15, 'Scheduling'), (20, 'Scheduled'), (25, 'Processing'), (30, 'Processed')], default=0),
        ),
    ]
